# Understanding Pandas Series and DataFrames - Lab

## Introduction

In this lab, let's get some hands on practice working with data cleanup using Pandas.

## Objectives
You will be able to:

* Manipulate columns in DataFrames (df.rename, df.drop)
* Manipulate the index in DataFrames (df.reindex, df.drop, df.rename)
* Manipulate column datatypes

## Let's get started!

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [53]:
df = pd.read_csv('turnstile_180901.txt')
print(len(df))
df.head()

197625

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,00:00:00,REGULAR,6736067,2283184
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,04:00:00,REGULAR,6736087,2283188
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,08:00:00,REGULAR,6736105,2283229
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,12:00:00,REGULAR,6736180,2283314
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,16:00:00,REGULAR,6736349,2283384

## Rename all the columns to lower case

In [4]:
df.columns = [x.lower() for x in df.columns]

In [6]:
df.columns

Index(['c/a', 'unit', 'scp', 'station', 'linename', 'division', 'date', 'time',
       'desc', 'entries',
       'exits                                                               '],
      dtype='object')

## Change the Index to be the Line Names

In [11]:
df.set_index('linename')
df

,c/a,unit,scp,station,linename,division,date,time,desc,entries,exits
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,00:00:00,REGULAR,6736067,2283184
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,04:00:00,REGULAR,6736087,2283188
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,08:00:00,REGULAR,6736105,2283229
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,12:00:00,REGULAR,6736180,2283314
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,16:00:00,REGULAR,6736349,2283384
5,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,20:00:00,REGULAR,6736562,2283425
6,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/26/2018,00:00:00,REGULAR,6736683,2283460
7,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/26/2018,04:00:00,REGULAR,6736696,2283461
8,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/26/2018,08:00:00,REGULAR,6736705,2283483
9,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/26/2018,12:00:00,REGULAR,6736746,2283524
10,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/26/2018,16:00:00,REGULAR,6736873,2283587
11,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/26/2018,20:00:00,REGULAR,6737067,2283631
12,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/27/2018,00:00:00,REGULAR,6737136,2283656
13,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/27/2018,04:00:00,REGULAR,6737146,2283658
14,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/27/2018,08:00:00,REGULAR,6737169,2283736
15,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/27/2018,12:00:00,REGULAR,6737301,2283965
16,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/27/2018,16:00:00,REGULAR,6737553,2284025
17,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/27/2018,20:00:00,REGULAR,6738257,2284091
18,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/28/2018,00:00:00,REGULAR,6738430,2284121
19,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/28/2018,04:00:00,REGULAR,6738442,2284126
20,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/28/2018,08:00:00,REGULAR,6738474,2284216
21,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/28/2018,12:00:00,REGULAR,6738621,2284402
22,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/28/2018,16:00:00,REGULAR,6738886,2284425
23,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/28/2018,20:00:00,REGULAR,6739630,2284478
24,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/29/2018,00:00:00,REGULAR,6739804,2284508
25,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/29/2018,04:00:00,REGULAR,6739812,2284512
26,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/29/2018,08:00:00,REGULAR,6739847,2284600
27,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/29/2018,12:00:00,REGULAR,6739986,2284838
28,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/29/2018,16:00:00,REGULAR,6740257,2284896
29,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/29/2018,20:00:00,REGULAR,6740888,2284941
...,...,...,...,...,...,...,...,...,...,...,...
197595,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/27/2018,01:00:00,REGULAR,5554,348
197596,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/27/2018,05:00:00,REGULAR,5554,348
197597,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/27/2018,09:00:00,REGULAR,5554,348
197598,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/27/2018,13:00:00,REGULAR,5554,348
197599,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/27/2018,17:00:00,REGULAR,5554,348
197600,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/27/2018,21:00:00,REGULAR,5554,348
197601,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/28/2018,01:00:00,REGULAR,5554,348
197602,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/28/2018,05:00:00,REGULAR,5554,348
197603,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/28/2018,09:00:00,REGULAR,5554,348
197604,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/28/2018,13:00:00,REGULAR,5554,348
197605,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/28/2018,17:00:00,REGULAR,5554,348
197606,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/28/2018,21:00:00,REGULAR,5554,348
197607,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/29/2018,01:00:00,REGULAR,5554,348
197608,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/29/2018,05:00:00,REGULAR,5554,348
197609,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/29/2018,09:00:00,REGULAR,5554,348
197610,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/29/2018,13:00:00,REGULAR,5554,348
197611,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/29/2018,17:00:00,REGULAR,5554,348
197612,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/29/2018,21:00:00,REGULAR,5554,348
197613,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/30/2018,01:00:00,REGULAR,5554,348
197614,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/30/2018,05:00:00,REGULAR,5554,348
197615,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/30/2018,09:00:00,REGULAR,5554,348
197616,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/30/2018,13:00:00,REGULAR,5554,348
197617,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/30/2018,17:00:00,REGULAR,5554,348
197618,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/30/2018,21:00:00,REGULAR,5554,348
197619,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/31/2018,01:00:00,REGULAR,5554,348
197620,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/31/2018,05:00:00,REGULAR,5554,348
197621,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/31/2018,09:00:00,REGULAR,5554,348
197622,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/31/2018,13:00:00,REGULAR,5554,348
197623,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/31/2018,17:00:00,REGULAR,5554,348
197624,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/31/2018,21:00:00,REGULAR,5554,348

## Change the index back

In [ ]:
# Your code here

## Create another column 'Num_Lines' that is a count of how many lines pass through a station. Then sort your dataframe by this column in descending order
*Hint: According to the [data dictionary](http://web.mta.info/developers/resources/nyct/turnstile/ts_Field_Description.txt), LINENAME represents all train lines that can be boarded at a given station. Normally lines are represented by one character. For example, LINENAME 456NQR represents trains 4, 5, 6, N, Q, and R.*

In [12]:
df['Num_Lines'] = df['linename'].map(lambda x: len(x))
df

,c/a,unit,scp,station,linename,division,date,time,desc,entries,exits,Num_Lines
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,00:00:00,REGULAR,6736067,2283184,7
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,04:00:00,REGULAR,6736087,2283188,7
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,08:00:00,REGULAR,6736105,2283229,7
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,12:00:00,REGULAR,6736180,2283314,7
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,16:00:00,REGULAR,6736349,2283384,7
5,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/25/2018,20:00:00,REGULAR,6736562,2283425,7
6,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/26/2018,00:00:00,REGULAR,6736683,2283460,7
7,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/26/2018,04:00:00,REGULAR,6736696,2283461,7
8,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/26/2018,08:00:00,REGULAR,6736705,2283483,7
9,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/26/2018,12:00:00,REGULAR,6736746,2283524,7
10,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/26/2018,16:00:00,REGULAR,6736873,2283587,7
11,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/26/2018,20:00:00,REGULAR,6737067,2283631,7
12,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/27/2018,00:00:00,REGULAR,6737136,2283656,7
13,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/27/2018,04:00:00,REGULAR,6737146,2283658,7
14,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/27/2018,08:00:00,REGULAR,6737169,2283736,7
15,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/27/2018,12:00:00,REGULAR,6737301,2283965,7
16,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/27/2018,16:00:00,REGULAR,6737553,2284025,7
17,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/27/2018,20:00:00,REGULAR,6738257,2284091,7
18,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/28/2018,00:00:00,REGULAR,6738430,2284121,7
19,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/28/2018,04:00:00,REGULAR,6738442,2284126,7
20,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/28/2018,08:00:00,REGULAR,6738474,2284216,7
21,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/28/2018,12:00:00,REGULAR,6738621,2284402,7
22,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/28/2018,16:00:00,REGULAR,6738886,2284425,7
23,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/28/2018,20:00:00,REGULAR,6739630,2284478,7
24,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/29/2018,00:00:00,REGULAR,6739804,2284508,7
25,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/29/2018,04:00:00,REGULAR,6739812,2284512,7
26,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/29/2018,08:00:00,REGULAR,6739847,2284600,7
27,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/29/2018,12:00:00,REGULAR,6739986,2284838,7
28,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/29/2018,16:00:00,REGULAR,6740257,2284896,7
29,A002,R051,02-00-00,59 ST,NQR456W,BMT,08/29/2018,20:00:00,REGULAR,6740888,2284941,7
...,...,...,...,...,...,...,...,...,...,...,...,...
197595,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/27/2018,01:00:00,REGULAR,5554,348,1
197596,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/27/2018,05:00:00,REGULAR,5554,348,1
197597,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/27/2018,09:00:00,REGULAR,5554,348,1
197598,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/27/2018,13:00:00,REGULAR,5554,348,1
197599,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/27/2018,17:00:00,REGULAR,5554,348,1
197600,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/27/2018,21:00:00,REGULAR,5554,348,1
197601,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/28/2018,01:00:00,REGULAR,5554,348,1
197602,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/28/2018,05:00:00,REGULAR,5554,348,1
197603,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/28/2018,09:00:00,REGULAR,5554,348,1
197604,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/28/2018,13:00:00,REGULAR,5554,348,1
197605,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/28/2018,17:00:00,REGULAR,5554,348,1
197606,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/28/2018,21:00:00,REGULAR,5554,348,1
197607,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/29/2018,01:00:00,REGULAR,5554,348,1
197608,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/29/2018,05:00:00,REGULAR,5554,348,1
197609,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/29/2018,09:00:00,REGULAR,5554,348,1
197610,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/29/2018,13:00:00,REGULAR,5554,348,1
197611,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/29/2018,17:00:00,REGULAR,5554,348,1
197612,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/29/2018,21:00:00,REGULAR,5554,348,1
197613,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/30/2018,01:00:00,REGULAR,5554,348,1
197614,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/30/2018,05:00:00,REGULAR,5554,348,1
197615,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/30/2018,09:00:00,REGULAR,5554,348,1
197616,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/30/2018,13:00:00,REGULAR,5554,348,1
197617,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/30/2018,17:00:00,REGULAR,5554,348,1
197618,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/30/2018,21:00:00,REGULAR,5554,348,1
197619,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/31/2018,01:00:00,REGULAR,5554,348,1
197620,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/31/2018,05:00:00,REGULAR,5554,348,1
197621,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/31/2018,09:00:00,REGULAR,5554,348,1
197622,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/31/2018,13:00:00,REGULAR,5554,348,1
197623,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/31/2018,17:00:00,REGULAR,5554,348,1
197624,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,08/31/2018,21:00:00,REGULAR,5554,348,1

## Write a function to clean a column name

In [13]:
def clean(col_name):
    cleaned = col_name.title()
    return cleaned

In [14]:
# This is a list comprehension. It applies your clean function to every item in the list.
# We then reassign that to df.columns
# You shouldn't have to change anything here.
# Your function above should work appropriately here.
df.columns = [clean(col) for col in df.columns]

In [15]:
# Checking the output, we can see the results.
df.columns

Index(['C/A', 'Unit', 'Scp', 'Station', 'Linename', 'Division', 'Date', 'Time',
       'Desc', 'Entries',
       'Exits                                                               ',
       'Num_Lines'],
      dtype='object')

## Group the Data by Day of Week and Plot the Sum of The Numeric Columns

In [55]:
df['DATE'] = pd.to_datetime(df.DATE, format='%m/%d/%Y').dt.day_name()
groupby_date = df.groupby('DATE').sum()
groupby_date

,ENTRIES,EXITS
DATE,,
Friday,1110224700078,906799065337
Monday,1114237052454,911938153513
Saturday,1115661545514,909142081474
Sunday,1192306179082,959223750461
Thursday,1122723988662,920691927110
Tuesday,1143313287046,942230721477
Wednesday,1123655222441,920630864687

In [58]:
groupby_date.index

Index(['Friday', 'Monday', 'Saturday', 'Sunday', 'Thursday', 'Tuesday',
       'Wednesday'],
      dtype='object', name='DATE')

## Group the Data by Weekend/Weekday and Plot the Sum of the Numeric Columns

In [60]:
mapping = {'Saturday': 'Weekend', 'Sunday': 'Weekend', 'Monday': 'Weekday',
           'Tuesday': 'Weekday', 'Wednesday': 'Weekday', 'Thursday': 'Weekday',
           'Friday': 'Weekday'}
groupby_weekday_or_end = groupby_date.groupby(mapping).sum()
groupby_weekday_or_end

,ENTRIES,EXITS
Weekday,5614154250681,4602290732124
Weekend,2307967724596,1868365831935

## Analysis Question: 

What is misleading about the day of week and weekend/weekday charts you just plotted?

In [ ]:
# Your answer here

## Drop a couple of columns

In [63]:
df.drop(columns = ['SCP'])

,C/A,UNIT,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
0,A002,R051,59 ST,NQR456W,BMT,Saturday,00:00:00,REGULAR,6736067,2283184
1,A002,R051,59 ST,NQR456W,BMT,Saturday,04:00:00,REGULAR,6736087,2283188
2,A002,R051,59 ST,NQR456W,BMT,Saturday,08:00:00,REGULAR,6736105,2283229
3,A002,R051,59 ST,NQR456W,BMT,Saturday,12:00:00,REGULAR,6736180,2283314
4,A002,R051,59 ST,NQR456W,BMT,Saturday,16:00:00,REGULAR,6736349,2283384
5,A002,R051,59 ST,NQR456W,BMT,Saturday,20:00:00,REGULAR,6736562,2283425
6,A002,R051,59 ST,NQR456W,BMT,Sunday,00:00:00,REGULAR,6736683,2283460
7,A002,R051,59 ST,NQR456W,BMT,Sunday,04:00:00,REGULAR,6736696,2283461
8,A002,R051,59 ST,NQR456W,BMT,Sunday,08:00:00,REGULAR,6736705,2283483
9,A002,R051,59 ST,NQR456W,BMT,Sunday,12:00:00,REGULAR,6736746,2283524
10,A002,R051,59 ST,NQR456W,BMT,Sunday,16:00:00,REGULAR,6736873,2283587
11,A002,R051,59 ST,NQR456W,BMT,Sunday,20:00:00,REGULAR,6737067,2283631
12,A002,R051,59 ST,NQR456W,BMT,Monday,00:00:00,REGULAR,6737136,2283656
13,A002,R051,59 ST,NQR456W,BMT,Monday,04:00:00,REGULAR,6737146,2283658
14,A002,R051,59 ST,NQR456W,BMT,Monday,08:00:00,REGULAR,6737169,2283736
15,A002,R051,59 ST,NQR456W,BMT,Monday,12:00:00,REGULAR,6737301,2283965
16,A002,R051,59 ST,NQR456W,BMT,Monday,16:00:00,REGULAR,6737553,2284025
17,A002,R051,59 ST,NQR456W,BMT,Monday,20:00:00,REGULAR,6738257,2284091
18,A002,R051,59 ST,NQR456W,BMT,Tuesday,00:00:00,REGULAR,6738430,2284121
19,A002,R051,59 ST,NQR456W,BMT,Tuesday,04:00:00,REGULAR,6738442,2284126
20,A002,R051,59 ST,NQR456W,BMT,Tuesday,08:00:00,REGULAR,6738474,2284216
21,A002,R051,59 ST,NQR456W,BMT,Tuesday,12:00:00,REGULAR,6738621,2284402
22,A002,R051,59 ST,NQR456W,BMT,Tuesday,16:00:00,REGULAR,6738886,2284425
23,A002,R051,59 ST,NQR456W,BMT,Tuesday,20:00:00,REGULAR,6739630,2284478
24,A002,R051,59 ST,NQR456W,BMT,Wednesday,00:00:00,REGULAR,6739804,2284508
25,A002,R051,59 ST,NQR456W,BMT,Wednesday,04:00:00,REGULAR,6739812,2284512
26,A002,R051,59 ST,NQR456W,BMT,Wednesday,08:00:00,REGULAR,6739847,2284600
27,A002,R051,59 ST,NQR456W,BMT,Wednesday,12:00:00,REGULAR,6739986,2284838
28,A002,R051,59 ST,NQR456W,BMT,Wednesday,16:00:00,REGULAR,6740257,2284896
29,A002,R051,59 ST,NQR456W,BMT,Wednesday,20:00:00,REGULAR,6740888,2284941
...,...,...,...,...,...,...,...,...,...,...
197595,TRAM2,R469,RIT-ROOSEVELT,R,RIT,Monday,01:00:00,REGULAR,5554,348
197596,TRAM2,R469,RIT-ROOSEVELT,R,RIT,Monday,05:00:00,REGULAR,5554,348
197597,TRAM2,R469,RIT-ROOSEVELT,R,RIT,Monday,09:00:00,REGULAR,5554,348
197598,TRAM2,R469,RIT-ROOSEVELT,R,RIT,Monday,13:00:00,REGULAR,5554,348
197599,TRAM2,R469,RIT-ROOSEVELT,R,RIT,Monday,17:00:00,REGULAR,5554,348
197600,TRAM2,R469,RIT-ROOSEVELT,R,RIT,Monday,21:00:00,REGULAR,5554,348
197601,TRAM2,R469,RIT-ROOSEVELT,R,RIT,Tuesday,01:00:00,REGULAR,5554,348
197602,TRAM2,R469,RIT-ROOSEVELT,R,RIT,Tuesday,05:00:00,REGULAR,5554,348
197603,TRAM2,R469,RIT-ROOSEVELT,R,RIT,Tuesday,09:00:00,REGULAR,5554,348
197604,TRAM2,R469,RIT-ROOSEVELT,R,RIT,Tuesday,13:00:00,REGULAR,5554,348
197605,TRAM2,R469,RIT-ROOSEVELT,R,RIT,Tuesday,17:00:00,REGULAR,5554,348
197606,TRAM2,R469,RIT-ROOSEVELT,R,RIT,Tuesday,21:00:00,REGULAR,5554,348
197607,TRAM2,R469,RIT-ROOSEVELT,R,RIT,Wednesday,01:00:00,REGULAR,5554,348
197608,TRAM2,R469,RIT-ROOSEVELT,R,RIT,Wednesday,05:00:00,REGULAR,5554,348
197609,TRAM2,R469,RIT-ROOSEVELT,R,RIT,Wednesday,09:00:00,REGULAR,5554,348
197610,TRAM2,R469,RIT-ROOSEVELT,R,RIT,Wednesday,13:00:00,REGULAR,5554,348
197611,TRAM2,R469,RIT-ROOSEVELT,R,RIT,Wednesday,17:00:00,REGULAR,5554,348
197612,TRAM2,R469,RIT-ROOSEVELT,R,RIT,Wednesday,21:00:00,REGULAR,5554,348
197613,TRAM2,R469,RIT-ROOSEVELT,R,RIT,Thursday,01:00:00,REGULAR,5554,348
197614,TRAM2,R469,RIT-ROOSEVELT,R,RIT,Thursday,05:00:00,REGULAR,5554,348
197615,TRAM2,R469,RIT-ROOSEVELT,R,RIT,Thursday,09:00:00,REGULAR,5554,348
197616,TRAM2,R469,RIT-ROOSEVELT,R,RIT,Thursday,13:00:00,REGULAR,5554,348
197617,TRAM2,R469,RIT-ROOSEVELT,R,RIT,Thursday,17:00:00,REGULAR,5554,348
197618,TRAM2,R469,RIT-ROOSEVELT,R,RIT,Thursday,21:00:00,REGULAR,5554,348
197619,TRAM2,R469,RIT-ROOSEVELT,R,RIT,Friday,01:00:00,REGULAR,5554,348
197620,TRAM2,R469,RIT-ROOSEVELT,R,RIT,Friday,05:00:00,REGULAR,5554,348
197621,TRAM2,R469,RIT-ROOSEVELT,R,RIT,Friday,09:00:00,REGULAR,5554,348
197622,TRAM2,R469,RIT-ROOSEVELT,R,RIT,Friday,13:00:00,REGULAR,5554,348
197623,TRAM2,R469,RIT-ROOSEVELT,R,RIT,Friday,17:00:00,REGULAR,5554,348
197624,TRAM2,R469,RIT-ROOSEVELT,R,RIT,Friday,21:00:00,REGULAR,5554,348

## Summary

Great! You practiced your data cleanup-skills using Pandas.